INSERT INTO ADDRESS (ID, STREETNAME, STREETNUMBER, ZIPCODE, CITY) VALUES ('1', 'Valhallavägen', '8', '11422', 'Stockholm');
INSERT INTO ADDRESS (ID, STREETNAME, STREETNUMBER, ZIPCODE, CITY) VALUES ('2', 'Årstaängsvägen', '13', '11775', 'Stockholm');
INSERT INTO ADDRESS (ID, STREETNAME, STREETNUMBER, ZIPCODE, CITY) VALUES ('3', 'Hägerstensvägen', '200', '12935', 'Stockholm');
INSERT INTO ADDRESS (ID, STREETNAME, STREETNUMBER, ZIPCODE, CITY) VALUES ('4', 'Rörstrandsgatan', '6', '11340', 'Stockholm');
INSERT INTO ADDRESS (ID, STREETNAME, STREETNUMBER, ZIPCODE, CITY) VALUES ('5', 'Sälgstigen', '27', '18162', 'Stockholm');
INSERT INTO ADDRESS (ID, STREETNAME, STREETNUMBER, ZIPCODE, CITY) VALUES ('6', 'Hotellgatan', '3', '17145', 'Stockholm');
INSERT INTO ADDRESS (ID, STREETNAME, STREETNUMBER, ZIPCODE, CITY) VALUES ('7', 'Ekebyhovsvägen', '1', '17810', 'Stockholm');

INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, HASCAR, ADDRESS_ID, USERNAME) VALUES ('1', 'Erik', 'Stannemark', true, (SELECT ID FROM ADDRESS WHERE (STREETNAME = 'Valhallavägen' AND STREETNUMBER = '8')), 'ERSTA');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, HASCAR, ADDRESS_ID, USERNAME) VALUES ('2', 'Nicole', 'Robertson', true, (SELECT ID FROM ADDRESS WHERE (STREETNAME = 'Hägerstensvägen' AND STREETNUMBER = '200')), 'NICOLE');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, HASCAR, ADDRESS_ID, USERNAME) VALUES ('3', 'Rebecca', 'Manhem', true, (SELECT ID FROM ADDRESS WHERE (STREETNAME = 'Rörstrandsgatan' AND STREETNUMBER = '6')), 'RENHE');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, HASCAR, ADDRESS_ID, USERNAME) VALUES ('4', 'Patrick', 'Hammarstedt', true, (SELECT ID FROM ADDRESS WHERE (STREETNAME = 'Sälgstigen' AND STREETNUMBER = '27')), 'PAHAA');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, HASCAR, ADDRESS_ID, USERNAME) VALUES ('5', 'Anders', 'Andersson', true, (SELECT ID FROM ADDRESS WHERE (STREETNAME = 'Hotellgatan' AND STREETNUMBER = '6')), 'ANERS');
INSERT INTO EMPLOYEE (ID, FIRSTNAME, LASTNAME, HASCAR, ADDRESS_ID, USERNAME) VALUES ('6', 'Mikael', 'Palm', true, (SELECT ID FROM ADDRESS WHERE (STREETNAME = 'Ekebyhovsvägen' AND STREETNUMBER = '1')), 'MIPAL');


INSERT INTO OFFICE (ID, NAME, ADDRESS_ID) VALUES ('1', 'Marievik', (SELECT ID FROM ADDRESS WHERE STREETNAME = 'Årstaängsvägen'));


INSERT INTO VEHICLE (ID, EMPLOYEE_ID, NUMOFSEATS, COSTPERMILE, LICENSEPLATE, MODEL) VALUES ('1', (SELECT ID FROM EMPLOYEE WHERE USERNAME = 'ERSTA'), '3', '50','HEJ123','Hummer');
INSERT INTO VEHICLE (ID, EMPLOYEE_ID, NUMOFSEATS, COSTPERMILE, LICENSEPLATE, MODEL) VALUES ('2', (SELECT ID FROM EMPLOYEE WHERE USERNAME = 'NICOLE'), '3', '50','BLA123','Mercedes');
INSERT INTO VEHICLE (ID, EMPLOYEE_ID, NUMOFSEATS, COSTPERMILE, LICENSEPLATE, MODEL) VALUES ('3', (SELECT ID FROM EMPLOYEE WHERE USERNAME = 'ANERS'), '4', '39','ABC111','Volvo');
INSERT INTO VEHICLE (ID, EMPLOYEE_ID, NUMOFSEATS, COSTPERMILE, LICENSEPLATE, MODEL) VALUES ('4', (SELECT ID FROM EMPLOYEE WHERE USERNAME = 'MIPAL'), '4', '43','DDR124','Volvo');

INSERT INTO CARRIDE (ID, VEHICLE_ID, RIDEDATE, EMPLOYEE_ID, OFFICE_ID, AVAILABLESEATS) VALUES ('1', (SELECT ID FROM VEHICLE WHERE LICENSEPLATE = 'HEJ123'), '2021-10-10', (SELECT ID FROM EMPLOYEE WHERE USERNAME = 'ERSTA'), (SELECT ID FROM OFFICE WHERE NAME = 'Marievik'), '2');
INSERT INTO CARRIDE (ID, VEHICLE_ID, RIDEDATE, EMPLOYEE_ID, OFFICE_ID, AVAILABLESEATS) VALUES ('2', (SELECT ID FROM VEHICLE WHERE LICENSEPLATE = 'BLA123'), '2021-10-10', (SELECT ID FROM EMPLOYEE WHERE USERNAME = 'NICOLE'), (SELECT ID FROM OFFICE WHERE NAME = 'Marievik'), '3');
INSERT INTO CARRIDE (ID, VEHICLE_ID, RIDEDATE, EMPLOYEE_ID, OFFICE_ID, AVAILABLESEATS) VALUES ('3', (SELECT ID FROM VEHICLE WHERE LICENSEPLATE = 'HEJ123'), '2021-10-11', (SELECT ID FROM EMPLOYEE WHERE USERNAME = 'ERSTA'), (SELECT ID FROM OFFICE WHERE NAME = 'Marievik'), '2');
INSERT INTO CARRIDE (ID, VEHICLE_ID, RIDEDATE, EMPLOYEE_ID, OFFICE_ID, AVAILABLESEATS) VALUES ('4', (SELECT ID FROM VEHICLE WHERE LICENSEPLATE = 'ABC111'), '2021-11-03', (SELECT ID FROM EMPLOYEE WHERE USERNAME = 'ANERS'), (SELECT ID FROM OFFICE WHERE NAME = 'Marievik'), '4');
INSERT INTO CARRIDE (ID, VEHICLE_ID, RIDEDATE, EMPLOYEE_ID, OFFICE_ID, AVAILABLESEATS) VALUES ('4', (SELECT ID FROM VEHICLE WHERE LICENSEPLATE = 'DDR124'), '2021-11-18', (SELECT ID FROM EMPLOYEE WHERE USERNAME = 'MIPAL'), (SELECT ID FROM OFFICE WHERE NAME = 'Marievik'), '4');